### ISSUE TITLE
sample prob

### ISSUE THREAD

**Issue by raudipra** [GaoangW/TNT#2]
Hello @GaoangW ,
 
I want to ask about sample prob variable (TNT/train_cnn_trajectory_2d.py) since I don't really get the data density part. I have tried to calculate it based on the number of images, the number of row in gt.txt and number of frames x number of classes as well. Yet, none of them gives the exact same probability as you wrote on your code.

My question is what does data density mean?

Thank you in advance

**Comment by GaoangW** [comment]
Hi @raudipra ,

The probability just represents the percentage of the number of unique objects among all the training data for each video. It is roughly calculated. It is only a sampling strategy in the training. A slight difference is also acceptable.
