### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by elun15** [GaoangW/TNT#3]
Hello

In ./AIC19/README.md >> 2D Tracking Testing >> Step 2 I am trying to download the model from the Google Drive link you provide, but access is denied. I already requested permissions, could you please give them to me? 

Thanks!

**Comment by GaoangW** [comment]
@elun15 Hello, I have given the permission.

**Comment by Imagesnn** [comment]
@GaoangW Hello，I also met the question of no permissions, and have applied for it. May I ask for your help? Thanks a lot!

**Comment by Imagesnn** [comment]
> @GaoangW Hello，I also met the question of no permissions, and have applied for it. May I ask for your help? Thanks a lot!

@GaoangW I have received the files you share. Thanks for your kind help.

**Comment by raudipra** [comment]
@GaoangW would you kindly share the files as well? I have submitted the permission request thanks!

**Comment by elun15** [comment]
> @elun15 Hello, I have given the permission.

@GaoangW  Thank you!

**Comment by woshiwoyali** [comment]
Can you give me a download permission?

**Comment by GaoangW** [comment]
Can you download the model from the link below?
https://drive.google.com/open?id=1mbJf08hJY0qXV2ZnMBHq-Bzw8U3Br54l

**Comment by GaoangW** [comment]
@woshiwoyali Certainly. Can you request the permission from the link below?
https://drive.google.com/open?id=1mbJf08hJY0qXV2ZnMBHq-Bzw8U3Br54l
