### ISSUE TITLE
ROI and detections

### ISSUE THREAD

**Issue by elun15** [GaoangW/TNT#4]
Hello, 
Just to confirm, because I have read nothing about this on the paper.

Are you using ROIs provided by the challenge in here?
https://github.com/GaoangW/TNT/blob/30b05e286dd8bb8d561eac1c1a0a73de41bc5756/AIC19/tracklet_utils_3c.py#L47  

Also, I suppose ssd detections are the provided as well ?
https://github.com/GaoangW/TNT/blob/30b05e286dd8bb8d561eac1c1a0a73de41bc5756/AIC19/tracklet_utils_3c.py#L49 

Thank you!

**Comment by GaoangW** [comment]
@elun15 The ROIs are provided in the shared folder. We used the provided ssd detection. You can also use your own detector.

**Comment by elun15** [comment]
> @elun15 The ROIs are provided in the shared folder. We used the provided ssd detection. You can also use your own detector.

Thanks!
