### ISSUE TITLE
How long does it take in image cropping?

### ISSUE THREAD

**Issue by Taaewoo** [GaoangW/TNT#5]
Hello @GaoangW 
I am wondering how long does it takes in image cropping?
I am training using MOT17 dataset and batch size is 32.
In your code, it takes about 4 minites to take a single for loop in 2 millions of loops.
It takes extremely long time for the image cropping.
Are there any mistake that I made in running your code?
So, I am wondering if there are any other way that I can save time for the image cropping.
I am running your code on a server machine with Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, 190G RAM, RTX 2080ti .
Looking forward to hearing from you soon.
Best Regards,

Park, Taewoo.

**Comment by GaoangW** [comment]
@Taaewoo Actually, the cropping usually takes much time. Usually, 6,000 loops are enough for the training. One possible way to save time is to save the cropped images in the memory.

**Comment by Taaewoo** [comment]
Thank you for your answer!
